# Generated by Django 5.1.5 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KelolaFAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pertanyaan', models.CharField(max_length=255)),
                ('jawaban', models.TextField()),
            ],
            options={
                'db_table': 'tb_faq',
            },
        ),
    ]
