# Generated by Django 5.1.5 on 2025-01-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kelolalayanan',
            table='tb_layanan',
        ),
    ]
