# Generated by Django 5.1.5 on 2025-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelolamobil',
            name='durasi',
            field=models.CharField(choices=[('Harian', 'Harian'), ('Mingguan', 'Mingguan'), ('Bulanan', 'Bulanan')], default='Harian', max_length=10),
        ),
        migrations.AlterModelTable(
            name='kelolamobil',
            table='db_mobil',
        ),
    ]
