# Generated by Django 5.1.5 on 2025-01-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0002_alter_kelolamobil_durasi_alter_kelolamobil_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kelolamobil',
            table='tb_mobil',
        ),
    ]
