# Generated by Django 5.1.5 on 2025-02-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0003_alter_kelolamobil_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelolamobil',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
