# Generated by Django 5.1.5 on 2025-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0004_kelolamobil_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelolamobil',
            name='durasi',
            field=models.CharField(choices=[('Harian', 'Harian'), ('Mingguan', 'Mingguan'), ('Bulanan', 'Bulanan')], default='Harian', max_length=50),
        ),
    ]
